# Generated by Django 2.1.7 on 2019-03-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('drapeau', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('num', models.IntegerField()),
                ('present', models.BooleanField(default=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.Equipe')),
            ],
        ),
    ]
