# Generated by Django 2.1.7 on 2019-03-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='equipe',
            new_name='equipe_id',
        ),
    ]
